### ISSUE TITLE
Missing module when running main.py

### ISSUE THREAD

**Issue by yann120** [ishan0102/vimGPT#21]
When I run the command main.py, I have the following error : 
```
➜  vimGPT git:(main) python main.py
Traceback (most recent call last):
  File "/Users/yann/Code/gpt/vimGPT/main.py", line 4, in <module>
    from whisper_mic import WhisperMic
ModuleNotFoundError: No module named 'whisper_mic'
```

**Comment by dayaasaagar** [comment]
Please include the file whisper_mic in your working location

**Comment by thiagobarbosa** [comment]
Maybe there's a simpler way, but I had to go through a few hoops.
First I installed portaudio:

`brew install portaudio`

.. so I could install pyaudio

`pip install pyaudio`

.. so I could install whisper_mic

`pip install whisper_mic`

Give it a shot and see if it helps.

And maybe some beautiful soul can shape up the `requirements.txt` file.
