### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'chat'

### ISSUE THREAD

**Issue by jaydhary14** [ishan0102/vimGPT#23]
python3 main.py
Initializing the Vimbot driver...
Navigating to Google...
Please enter your objective: latest news
Capturing the screen...
Getting actions for the given objective...
Traceback (most recent call last):
  File "/Users/jaydeep/git/vimGPT/main.py", line 54, in <module>
    main_entry()
  File "/Users/jaydeep/git/vimGPT/main.py", line 49, in main_entry
    main(args.voice)
  File "/Users/jaydeep/git/vimGPT/main.py", line 35, in main
    action = vision.get_actions(screenshot, objective)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaydeep/git/vimGPT/vision.py", line 27, in get_actions
    response = openai.chat.completions.create(
               ^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'chat'

**Comment by jaydhary14** [comment]
I am running on MacBook M1

**Comment by ishan0102** [comment]
What version of the `openai` package are you on? Did you install requirements with `pip install -r requirements.txt`?

**Comment by jaydhary14** [comment]
that fix it, I had wrong version of openapi .. also had to set my api key in as an env variables
